### ISSUE TITLE
Use Headless Chrome as next Browser Engine

### ISSUE THREAD

**Issue by stefanzweifel** [stefanzweifel/screeenly#83]
After the announcement of [Headless Chrome](https://www.chromestatus.com/features/5678767817097216) the maintainer of PhantomJs announced that he will step down from the project.

The currently used Browser Engine is PhantomJs and always had it's flaws (See #59 , #44). Now that Headless Chrome is coming it's time to make the switch and use a more stable Browser Engine.

## Links:

- https://developers.google.com/web/updates/2017/04/headless-chrome

## TODOs

- [x] Find or write a Package that interacts with the Chrome Binary
- [x] Create new `HeadlessChromeBrowser` which implements `CanCaptureScreenshot`
- [x] (BETA Test the new engine?)

**Comment by hbakhtiyor** [comment]
interaction with chrome goes through chrome debugging protocol which [not yet available](https://developer.chrome.com/devtools/docs/debugging-clients) for php

>  Implement Headless Chrome

what do you mean by "implement"?

**Comment by stefanzweifel** [comment]
Hey,

by "implementing" `chrome-headless` I mean to write an implementation of the `CanCaptureScreenshot` interface. [Here's the PhantomJs](https://github.com/stefanzweifel/screeenly/blob/master/modules/Screeenly/Services/PhantomsJsBrowser.php) implementation currently used.

And yeah, there isn't an official php package yet, but this shouldn't stop us from using it in php applications.

It could be something simple as this:

```php
<?php

$output = shell_exec('chrome --headless --disable-gpu --screenshot https://www.chromestatus.com/');
```

The problem I currently see here is, that you can't define the name of the screenshot file or you can't pipe it into another application. When screeenly would get multiple requests in the same second this would cause some errors.

**Comment by hbakhtiyor** [comment]
better to communicate with their protocol

**Comment by stefanzweifel** [comment]
Of course it would be better if we could communicate with the Chrome Debugging Protocol directly, but for a first test / draft it would be great if we could just use the binary directly.

**Comment by stefanzweifel** [comment]
PhantomJs has been replaced with Chrome Headless in #87. The new version is currently being deployed.
